[package]
name = "rsloc"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.6.7", features = ["derive"] }
proc-macro2 = { version = "1.0.107", features = ["span-locations"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
syn = { version = "3.0.6", features = ["full", "visit"] }
